/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.cat.eye.performance.test.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
